config/routes.rb
Tasktime::Application.routes.draw do
  
  resources :sessions

  resources :tasks
  devise_for :users
  devise_scope :user do 
    root to: 'home#home'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
    delete 'logout', to: 'home#logout'

  end

  post 'home/end_session' => 'home#end_session', :as => :end_session
  post 'tasks/create_session' => 'tasks#create_session', :as => :create_session
  post 'tasks/start_timer' => 'tasks#start_timer', :as => :start_timer
  post 'tasks/stop_timer' => 'tasks#stop_timer', :as => :stop_timer

  get 'tasks/show_sessions/:id' => 'tasks#show_sessions'
  get 'home/task_table' => 'home#task_table'

  root :to => "home#home"

end

app/views/devise2/new.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
dsafasdf sd
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>sadsdf asdf 

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "users/shared/links" %>