tasktime/config/routes.rb
Tasktime::Application.routes.draw do
  
  resources :sessions

  resources :tasks
  devise_for :users
  devise_scope :user do 
    root to: 'home#home'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  post 'tasks/create_session' => 'tasks#create_session', :as => :create_session
  post 'tasks/start_timer' => 'tasks#start_timer', :as => :start_timer
  post 'tasks/stop_timer' => 'tasks#stop_timer', :as => :stop_timer
  get 'tasks/show_sessions/:id' => 'tasks#show_sessions'
  root :to => "home#home"

end

tasktime/app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :task
  attr_accessible :duration, :end, :start, :note

  after_save :update_completed

  def update_completed
  	complete = 0
  	task.sessions.each do |session|
  		puts "duration:"
  		puts session.duration
  		complete+= session.duration
  	end
  	task.completed = complete / 60
  	puts ""
  	puts ""
  	puts ""
  	puts "\n\n\n\n\n\n\n\n\n\n"
  	puts "completed: "
  	puts task.completed
  	puts task.name
  	task.save
  end
end

tasktime/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :sessions
  attr_accessible :completed, :name, :goal, :time_period, :description
  # attr_accessible :title, :body
 
  scope :ending_by, lambda {|time| where("end_date < ?", time)}


  def self.test(id)
  	puts "id: "
  	puts id
  end
  
  def self.update_completed
  	return completed
  end
end

tasktime/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body

  has_many :tasks
end

tasktime/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

tasktime/app/controllers/home_controller.rb
class HomeController < ApplicationController
	include HomeHelper
  def home
  	@cur_user = current_user
  	@tasks = case params[:sort]
  	when "name"
  		@cur_user.tasks.order("name")
  	when "ending_in"
  		@cur_user.tasks.order("end_date ASC")
  	when "percentage"
  		sort_percentage(@cur_user.tasks)
  	when "hours_until_goal"
  		sort_hours_until_goal(@cur_user.tasks)
  	else
      @cur_user.tasks if @cur_user
  	end


  end

  def show

  end
end

tasktime/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :set_session, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @sessions = Session.all

    respond_with(@sessions)
  end

  def show
    respond_with(@session)
    @task = Task.find(params[:id])
    render :layout => false
  end

  def new
    @session = Session.new
    respond_with(@session)
  end

  def edit
  end

  def create
    @session = Session.new(params[:session])
    respond_with(@session)
  end

  def update
    @session.update_attributes(params[:session])
    respond_with(@session)
  end

  def destroy
    @session.destroy
    respond_with(@session)
  end

  private
    def set_session
      @session = Session.find(params[:id])
    end
end

tasktime/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :set_task, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tasks = Task.all
    respond_with(@tasks)
  end

  def show
    @task = Task.find(params[:id])
    @duration = 1
    respond_with(@task)

  end

  def new
    @task = Task.new
    @cur_user = current_user
    puts "\n\n\n\n\n\n"
    puts "TASK - NEW"
    puts "\n\n\n\n\n\n"
        puts "-"
    puts current_user
    puts "-"
    render :partial => "home/new_task_modal"
  end

  def edit
  end

  def create
    puts "-"
    puts current_user
    puts "-"
    @task = Task.new(params[:task])
    @task.completed = 0
    @task.end_date = DateTime.now + @task.time_period.hours
    @task.start_date = DateTime.now
    current_user.tasks << @task

    redirect_to :controller => "home", :action => "home"
  end

  def update
    @task.update_attributes(params[:task])
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end


  def start_timer
    @duration = @duration
    @start = params[:start]
    @end = params[:end]
  end

  def create_session
    puts params
    puts "\n\n\n\n\nCREATE SESSION \n\n\n\n"
    @task = Task.find(params[:task_id])
    @session = Session.new(start: Time.at(params[:start].to_i), duration: params[:duration], end: Time.at(params[:end].to_i), note: params[:note])
    Task.find(params[:task_id]).sessions << @session
  end

  def show_sessions
    puts "\n\n\n\n\n\n\n SHOW SESSIONS \n\n\n\n\n\n"
    @task = Task.find(params[:id])
    render :partial => "sessions", :layout => false
  end


  private
    def set_task
      @task = Task.find(params[:id])
    end
end

tasktime/app/helpers/application_helper.rb
module ApplicationHelper
	def hours_in_words(hours)
		distance_of_time_in_words(Time.at(0), Time.at(hours) * 3600)
	end

def format_minutes(minutes)
		hours = minutes / 60
		mins = minutes % 60

		return format("%02d:%02d", hours, mins)
	end
end

tasktime/app/helpers/home_helper.rb
module HomeHelper
	def task_percentage(task)
		return ((task.completed.to_f / task.goal) * 100).to_i

	end

	def ending(task)
		hours = (((task.end_date - DateTime.now) / 1.hour).round)
		days = ((task.end_date - DateTime.now) / 1.day).round


		if hours < 24
			return hours.to_s + " Hours"
		else
			return days.to_s + " Days, " + (hours % 24).to_s + " Hours"
		end
	end



	def format_minutes(minutes)
		hours = minutes / 60
		mins = minutes % 60

		return format("%02d:%02d", hours, mins)
	end

	def sort_percentage(tasks) 
		tasks.sort{|a, b| task_percentage(a) <=> task_percentage(b)}
	end

	def sort_hours_until_goal(tasks) 
		tasks.sort{|a, b| (a.goal - a.completed) <=> (b.goal - b.completed)}
	end

	def sort_timeleft(tasks)
		
	end

end




def sort_ending(tasks)
	tasks.sort{|a, b| a.end_date <=> b.end_date}
end

def sort_created(tasks)
	tasks.sort{|a, b| b.created_at <=> a.created_at}
end

tasktime/app/helpers/sessions_helper.rb
module SessionsHelper
end

tasktime/app/helpers/tasks_helper.rb
module TasksHelper
	def hours_in_words(hours)
		distance_of_time_in_words(Time.at(0), Time.at(hours * 3600))
	end

	def longest_session(sessions)
		longest = 0
		sessions.each do |session|
			if session.duration > longest
				longest = session.duration
			end
		end
		longest
	end

	def percent_of_longest(session, longest) #instead use % of average session times 2
		#longest = sessions
		total = 0
		longest.each do |l|
			total = total + l.duration
		end
		total = total / longest.size
		#(session.duration.to_f / longest) * 100
		(session.duration.to_f / (total * 2)) * 100
	end

	def seconds_in_time(seconds)
		hours = seconds / 3600
		mins = (seconds / 60) % 60

		return format("%02d:%02d", hours, mins)
	end
end

tasktime/app/views/home/_new_task_modal.html.erb
	<div class="modal-dialog">
	  	<div class="modal-content">
	        <div class="modal-header">
	          	<h4 class="modal-title" id="new-task-label">New Task</h4>
	        </div>
	        <div class="modal-body">
	        	<%= form_for @task, :remote => true, :html=> {:id => 'task-form'} do |f| %>
	          		<text class="form-label">Task Name: </text> <span class="form-field"><%= f.text_field :name %> </span> 
	          		<br><br>

	          		<text class="form-label">Goal (mins): </text> <span class="form-field"><%= f.text_field :goal %> </span> 
	          		<br><br>

	          		<text class="form-label">Time Period (hours): </text> <span class="form-field"><%= f.text_field :time_period %> </span> 
	          		<br><br>

	          		<text class="form-label">Description: </text> <span class="form-field"><%= f.text_area :description, size: "75x3" %> </span> 
	          		<br><br>
	          	<% end %>
	          	
	        </div>
	        <div class="modal-footer">
	          	<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
	          	<button type="button" class="btn btn-success" id="submit-task" > Submit </button>
	        </div>
	    </div>
	</div>

tasktime/app/views/home/_table.html.erb
<table>
  <thead>
    <tr>
    	
      <th><%= link_to "Name", :sort => "name"%></th>
      <th><%= link_to "% Completed", :sort => "percentage"%></th>
      <th><%= link_to "Work Left", :sort => "hours_until_goal"%></th>
      <th><%= link_to "Goal", :sort => "goal" %></th>
      <th><%= link_to "Ending in", :sort => "ending_in"%></th>
      
    </tr>
  </thead>
  
  <tbody>
	<% @tasks.each do |task| %>
		<tr class="row-<%= task.id %>">

			<td class="table-name table-name-<%= task.id %>"> <strong><%= link_to task.name, task %></strong> </td>
			<td class="table-percent table-percent-<%= task.id %>"> 

				<div class="percent-bar percent-bar-<%= task.id %>"></div>
				<p class="percent-text percent-text-<%= task.id %>">
					<b><%= task_percentage(task) %>%</b>
				</p>
			
			</td>
			<td class="table-completed table-completed-<%= task.id %>"><%= format_minutes(task.goal - task.completed) %> Hours</td>

			<td class="table-goal table-goal-<%= task.id %>"> <%= format_minutes(task.goal) %> Hours </td>
			<td class="table-timeleft table-timeleft-<%= task.id %>"> <%= ending(task) %> </td>

		</tr>
	<% end %>

  </tbody>
  
</table>

tasktime/app/views/home/_task_form.html.erb
<%= form_for @task do |f| %>
	          		<%= f.text_field :name %>
	          		<%= f.text_field :goal %>

	          	<% end %>

tasktime/app/views/home/home-backup.html.erb
<head>
<%= stylesheet_link_tag    "home", :media => "all" %>

	<style type="text/css" rel="stylesheet">
	<% if user_signed_in? %>
		<% num = 0 %>
		<% @cur_user.tasks.each do |task| %>

			.meter-bar-<%= task.id %> {
				background-color: #2a2;
				width: <%= task_percentage(task) %>%;
				border-radius: 3px;
			}



			<% num = num + 1 %>
		<% end %>
	<% end %>

	</style>

	
</head>


<% if !user_signed_in? %>
<div class="container main-div">
	<div class="row main-div">
		<div class="col-sm-10 main-div">
		asdfsdf
			<p>Welcome to TaskTimer, the simplest and easiest solution for time management and tracking, with no setup required!</p>
			<br>
			asdfasdf
			<p>Sign in or Register to start tracking your tasks instantly!</p>
		</div> <!-- column -->
		
	</div> <!-- main row -->
</div> <!-- container -->

<% else %> <!-- logged in -->

	<div class="container login-container">
		<div class="row login-row">
		<div class="col-sm-2"></div>
			<div class="col-sm-8 login-col main-div">
				<div class="top-area">
					<p class="users-tasks-text">
						<h3><b><%= @cur_user.username %>'s Tasks</b></h3>
					</p>
				</div>

				<br>
				<br>
			<% num = 0 %>
				<% @cur_user.tasks.each do |task| %>
					<div class="row task-row">
						<div class="col-sm-12 task-col">
							<p class='task-desc'><%= task.description %></p>
							<h2 class='task-name'><%= task.name %></h3>
						</div>

						<!-- METER AREA -->
						<div class="col-sm-2"></div>
						<div class="col-sm-8 meter-container">
							<!--Just Above Meter -->
							<p class="time-period time-period-<%= task.id %>">1 Week</p>
							<p class="time-remaining time-remaining-<%= task.id %>">4 days</p>

							<!-- Meter -->
							<div class="meter-back"></div>
							<div class="meter-bar meter-bar-<%= task.id %>"></div>
							<p class="meter-percent"><b><%= task_percentage(task) %>% </b></p>

							<!-- Just Below Meter -->
							<p class="time-completed time-completed-<%= task.id %>">Completed: <%= format_minutes(task.completed) %> / <%= format_minutes(task.goal) %> Hours</p>

						</div> 
						<!-- METER AREA -->

						<div class="col-sm-12 task-button-col">
							<div class="button-div">
								<span class="timer-buttons">
									<button type="button" id="quick-timer-<%= task.id %>" onclick="changeName(this, <%= task.id %>)" class="btn btn-success start-btn">Quick Timer</button>
									<!-- <button type="button" id="start-<%= task.id %>" class="btn btn-danger stop-btn">Stop Timing</button> -->
								</span>
								<div class="button-to-wrap"> <!-- fix formatting because button_to wraps button in a form -->
									<%= button_to("Show Task", {:controller => :tasks, :action => 'show', :id => task.id, remote: true}, {:method => :get, :class => "btn btn-primary task-btn"}) %>
								</div>
								<div class="button-to-wrap"> <!-- fix formatting because button_to wraps button in a form -->
									<button type="button" class="btn btn-danger btn-small delete-btn">Delete</button>
								</div>

								<div class="timer-area" id="timer-<%= task.id %>">
									<p id="seconds">0</p>
									<br>
									10:40
								</div>

							</div>
						</div>
						<div class="col-sm-2"></div>


					</div> <!-- Task Row -->
					<% num = num + 1 %>
				<% end %>


			</div>
		</div>
	</div>
<% end %>

tasktime/app/views/home/home.html.erb
<head>

<%= stylesheet_link_tag    "home", :media => "all" %>

<style type="text/css" rel="stylesheet">
	<% if user_signed_in? %>
		<%  @cur_user.tasks.each do |task| %>

			.meter-bar-<%= task.id %> {
				background-color: #2a2;
				width: <%= task_percentage(task) %>%;
				max-width: 100%;
				border-radius: 3px;
			}

			.percent-bar-<%= task.id %> {
				width: <%= task_percentage(task) %>%;
				max-width: 100%;
			}
			

		<% end %>

	<% end %>
</style>

	
</head>
<body>


<% if @cur_user %>
<div class="header-div">

	<h1 class="my-tasks"><%= @cur_user.username %>'s Tasks</h1>




	<button class="btn btn-primary modal-button" data-remote="true" onclick="show_task_modal()">
    	New Task
  	</button>

  <!-- Modal -->
  	<div class="modal fade" id="new-task-modal" tabindex="-1" role="dialog" aria-labelledby="new-task-label" aria-hidden="true">
	  
	</div>

</div>


<br>
<br>
<div id="table-partial-div">
	<%= render(:partial => "table") %>
</div>

<% end %>

</body>

tasktime/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasktime</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">

      <div class="navbar-header">
        <a class="navbar-brand" href="/">Task-Time</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Tasks</a></li>

      </ul>

      <ul class='nav navbar-nav pull-right nav-login'>

        <% if user_signed_in? %>
          <li><a href="#" id='username'><%= current_user.username %></a></li>
          <li class="active">  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          <li></li>
          <li> </li>
        <% else %>
          <li><a href="/users/sign_in">Sign in</a></li>
          <li><a href="/users/sign_up">Register</a></li>
        <% end %>
      </ul>

  </div> <!-- container -->
</nav>


<%= yield %>

</body>
</html>

tasktime/app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tasktime/app/views/tasks/_new_session.html.erb
<% session = Session.new %>
<% session.task = @task %>
<% session.duration = 0 %>
<% session.start = 0 %>
<% session.end = 0 %>
<!-- Move the above code to controller when New Session button is set up -->
<div id="new-session" class="new-session session-col">
	<div class="new-session-holder">
		<div class="session-title new-title">
			<%= session.task.name %> <br>
		</div>

		<div class="new-content session-content"> <!-- SESSION CONTENT -->

			<div class="new-circle circle">
				<div class="circle-cover">
					<div class="circle2">
								
					</div>
				</div>
					<span class="session-duration session-duration-new"> 00:00:00</span>
			</div>

			<div class="new-buttons">
				<span class="but-wrap">
					<%= button_to "Start", {:action => "start_timer", :controller => "tasks", :start => session.start}, :method => :post, :remote => true, class: "btn btn-success btn-start session-btn" %>

					<button type="button" class="btn btn-danger btn-stop session-btn" onclick="stopTimer(<%= @task.id %>)">Stop</button>
				</span>

			</div>

			<div class="new-text new-note session-text session-note">
				<textarea id="note-text-new">Enter session note here.</textarea>
			</div>

			<span class="new-links">

				<%= link_to "Delete", {:action => "start_timer", :controller => "tasks"}, :method => :post, :remote => true, class: "new-delete" %> - 
				<a id="save_new" onclick="save_new()">Save</a>
							
			</span>

		</div> 		<!-- SESSION CONTENT -->

	</div> <!-- New Session Holder -->
</div><!-- New Session -->

tasktime/app/views/tasks/_sessions.html.erb
<style>
	<% longest = longest_session(@task.sessions) %>
	<% @task.sessions.each do |session| %>
		<% percent = percent_of_longest(session, @task.sessions) %>
		.circle-cover-<%= session.id %> {
			height: <%= percent %>%;
		}

		.circle2-<%= session.id %> {
			height: <%= (100 / percent) * 100 %>%;
		}
	<% end %>
</style>

<script>
console.log("RENDER SESSIONS");
</script>
<div class="container-fixed session-container">

	<div class="session-header-div"><h2 class="session-header">Sessions</h2></div>
	<div class="row session-row">
		<div class="column-wrap">



<% count = 0 %>
<% first = true %>

<!-- display new session button, and if it exists, the first session, double-column session display wrapper -->

	<div class="col-md-6 session-splitter"><!-- start the session splitter, holds 2 sessions -->
		<div class="col-sm-6 session-wrap"><!-- div to wrap sessions, for display/style purposes -->
			<div id="new-ses-btn" class="new-session-button"><!-- display new session button in first session box -->
				<button onclick="show_new_session()" class="btn btn-primary new-session-btn">+ New Session</button>
			</div>
		<%= render(:partial => "new_session", :task => @task) %><!--render new session partial, hidden until btn is clicked-->
		</div>

		<% if @task.sessions[0] %> <!-- if there are any sessions -->
			<% session = @task.sessions[0] %> <!-- set session to the first session of the task -->

			<!-- and display the first session inside 'session-splitter' with new session button -->
			<div class="col-sm-6 session-wrap">
				<div class="session-col">

					<div class="session-title session-title-<%= session.task.name %>">
						<%= session.task.name %> <br>
					</div>

					<div class="session-content"> <!-- SESSION CONTENT -->
						<span class="session-text session-date session-date-<%= session.id %>"> <%= session.start.to_date %></span>
						<span class="session-text session-id session-id-<%= session.id %>"> <%= session.id %></span>


						<div class="circle circle-<%= session.id %>">
							<div class="circle-cover circle-cover-<%= session.id %>">
							<div class="circle2 circle2-<%= session.id %>">
								
							</div>
							</div>


							<span class="session-duration session-duration-<%=session.id %>"> <%= seconds_in_time(session.duration) %></span>
						</div>


						<span class="session-text session-time session-time-<%= session.id %>"> <%= session.start.strftime("%I:%M %P") %> - <%= session.end.strftime("%I:%M %P") %></span>

						<span class="session-text session-links session-links-<%= session.id %>"> <%= link_to 'Edit' %> | <%= link_to 'Delete' %></span>

						<div class="session-text session-note session-note-<%= session.id %>"> <%= session.note %> </div>
					</div> 		<!-- SESSION CONTENT -->

				</div> <!-- Session col -->
			</div> <!-- Session Wrap (inner 6-col) -->


		<% end %>

	</div>


<!-- drop(1) to skip over first element, because if it exists it will be displayed in the first 'session-splitter' along
with the new task button. bootstrap won't display columns to responsively drop from 4 to 2 to 1 cols as screen size gets 
smaller, so I had to implement my own solution and this is the one annoying side effect of that hack I need to work around -->
<% @task.sessions.drop(1).each do |session| %> <!-- Display all session;  TODO: add show:this week/day/etc. and paginate -->
	<% count = count + 1 %> 

	<% if count == 1 then %>
		
			<div class="col-md-6 session-splitter">

	<% end %>



			<div class="col-sm-6 session-wrap">
				<div class="session-col">

					<div class="session-title session-title-<%= session.task.name %>">
						<%= session.task.name %> <br>
					</div>

					<div class="session-content"> <!-- SESSION CONTENT -->
						<span class="session-text session-date session-date-<%= session.id %>"> <%= session.start.to_date %></span>
						<span class="session-text session-id session-id-<%= session.id %>"> <%= session.id %></span>


						<div class="circle circle-<%= session.id %>">
							<div class="circle-cover circle-cover-<%= session.id %>">
							<div class="circle2 circle2-<%= session.id %>">
								
							</div>
							</div>


							<span class="session-duration session-duration-<%=session.id %>"> <%= seconds_in_time(session.duration) %></span>
						</div>


						<span class="session-text session-time session-time-<%= session.id %>"> <%= session.start.strftime("%I:%M %P") %> - <%= session.end.strftime("%I:%M %P") %></span>

						<span class="session-text session-links session-links-<%= session.id %>"> <%= link_to 'Edit' %> | <%= link_to 'Delete' %></span>

						<div class="session-text session-note session-note-<%= session.id %>"> <%= session.note %> </div>
					</div> 		<!-- SESSION CONTENT -->

				</div> <!-- Session col -->
			</div> <!-- Session Wrap (inner 6-col) -->


	<% if count == 2 then %>

			</div> <!-- Session Splitter (outer 6-col) -->
			<% count = 0 %>

	<% end %>

		<% end %>

		</div> <!-- Session Col -->
	</div><!-- Session Row -->
</div><!-- Session container -->

tasktime/app/views/tasks/_table.html.erb
<table class="task-table">
  <thead>
    <tr>
    	
      <th colspan="4" class="table-header"><%= @task.name %></th>

    </tr>
  </thead>
  
  <tbody>
		<tr class="row-description row-description-<%= @task.id %>">
			<td class="task-property">Description</td>
			<td class="task-value task-description task-description-<%= @task.id %>"><%= @task.description %></td>
			<td class="edit"><a href="#">Edit</a></td>
		</tr>

		<tr class="row-completed row-completed-<%= @task.id %>">
			<td class="task-property">Completed</td>
			<td class="task-completed task-value"><%= format_minutes(@task.completed) %> Hours</td>
			<td class="edit"><a href="#">Edit</a></td>
		</tr>

		<tr class="row-goal row-goal-<%= @task.id %>">
			<td class="task-property">Goal</td>
			<td class="task-value task-goal"><%= format_minutes(@task.goal) %> Hours</td>
			<td class="edit"><a href="#">Edit</a></td>
		</tr>

		<tr class="row-percent row-percent-<%= @task.id %>">
			<td class="task-property">Percent Completed</td>
			<td class="task-value task-percent"><%= task_percentage(@task) %></td>
			<td class="edit"><a href="#">Edit</a></td>
		</tr>

		<tr class="row-time-period row-time-period-<%= @task.id %>">
			<td class="task-property">Time Period</td>
			<td class="task-value task-period"><%= hours_in_words(@task.time_period) %></td>
			<td class="edit"><a href="#">Edit</a></td>
		</tr> 

		<tr class="row-time-left row-time-left-<%= @task.id %>">
			<td class="task-property">Time Left</td>
			<td class="task-value task-left"><%= ending(@task) %></td>
			<td class="edit"><a href="#">Edit</a></td>
		</tr>

		<tr class="row-recurring row-recurring-<%= @task.id %>">
			<td class="task-property">Recurring?</td>
			<td class="task-value task-recurring"> NO </td>
			<td class="edit"><a href="#">Edit</a></td>
		</tr>


  </tbody>
  
</table>

tasktime/app/views/tasks/create_session.js.erb
reset_timer();
console.log("CREATE SESSION JS")
$('#sessions-partial').load('/tasks/show_sessions/<%= @task.id %>');
            console.log("redraw");

$('.task-completed').html("<%= format_minutes(@task.completed) %>" + " Hours");

tasktime/app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

tasktime/app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.user %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

tasktime/app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

tasktime/app/views/tasks/show.html.erb
<head>
<%= stylesheet_link_tag    "tasks", :media => "all" %>
</head>

<body>
	<div class="task-head-div">
		<h2 class="task-head"><%= @task.name %></h2>
		<h3 class="head-back"><a href="/">Back</a></h3>
	</div>

	<div id="table-partial">
		<%= render(:partial => "table") %>
	</div>



	<div id="sessions-partial">
		<%= render(:partial => "sessions") %>
	</div>
</body>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

tasktime/app/views/tasks/show_sessions.js.erb
var seconds = 0;
var timing = false;
var startTime = null;
var endTime = null;
var task_id = 90;

tasktime/app/views/tasks/start_timer.js.erb
	startTimer();

tasktime/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>